CREATE  TABLE PIZZA_SALES
(
  pizza_id INTEGER PRIMARY KEY,
  order_id INTEGER,
  pizza_name_id TEXT,
  quantity INTEGER,
  order_date DATE,
  order_time TIME,
  unit_price NUMERIC(10,2),
  total_price NUMERIC (10,2),
  pizza_size VARCHAR(10),
  pizza_category VARCHAR(50),
  pizza_ingredients TEXT,
  pizza_name TEXT
)

SELECT * FROM PIZZA_SALES;

-- KPI'S
-- 1. TOTAL REVENUE

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;

-- 2. TOTAL_ORDERS

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;

-- 3. AVERAGE ORDER_VALUE

SELECT CAST(CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) / 
CAST(COUNT(DISTINCT ORDER_ID)AS DECIMAL(10,2))AS DECIMAL(10,2)) AS AVG_ORDER_VALUE 
FROM PIZZA_SALES;

-- 4. TOTAL PIZZA SOLD

SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM PIZZA_SALES;

-- 5. AVERAGE PIZZA PER ORDER

SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2)) / 
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS AVG_PIZZA_PER_ORDER
FROM PIZZA_SALES;


-- ANALYSIS (CHART REQUIREMENT)
-- 1. MONTHLY TREND FOR TOTAL REVENUE

SELECT TO_CHAR(ORDER_DATE, 'MONTH') AS MONTH, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'MONTH') 

-- 2. DAILY TREND FOR TOTAL ORDERS 

SELECT TO_CHAR(ORDER_DATE, 'DAY') AS DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'DAY');

-- 3. % OF SALES BY PIZZA CATEGORY 

SELECT PIZZA_CATEGORY, SUM(TOTAL_PRICE)AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100 / 
(SELECT SUM(TOTAL_PRICE)  FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES 
GROUP BY PIZZA_CATEGORY;

-- 4. % OF SALES BY PIZZA SIZE

SELECT PIZZA_SIZE, SUM(TOTAL_PRICE) AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100 / 
(SELECT SUM(TOTAL_PRICE)  FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES 
GROUP BY PIZZA_SIZE;

-- 5. TOTAL PIZZA SOLD BY PIZZA SIZE AND CATEGORY 
SELECT PIZZA_SIZE,SUM(QUANTITY) AS TOTAL_PIZZA_SOLD 
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

SELECT PIZZA_CATEGORY,
SUM(QUANTITY) AS TOTAL_PIZZA_SOLD 
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

-- 6. REVENUE BY PIZZA NAME 
SELECT PIZZA_NAME,
SUM(TOTAL_PRICE) AS TOTAL_REVENUE_BY_NAME 
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE_BY_NAME DESC
LIMIT 5;

-- TOP & BOTTOM ANALYSIS
-- 1. TOP PIZZA BY REVENUE

SELECT PIZZA_NAME,
SUM(TOTAL_PRICE) AS TOTAL_REVENUE_BY_NAME 
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE_BY_NAME DESC
LIMIT 5;

-- 2. WORST PIZZA BY REVENUE

SELECT PIZZA_NAME,
SUM(TOTAL_PRICE) AS TOTAL_REVENUE_BY_NAME 
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE_BY_NAME ASC
LIMIT 5;

-- 3. TOP PIZZA BY ORDERS
SELECT PIZZA_NAME,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;

-- 4. WORST PIZZA BY ORDERS
SELECT PIZZA_NAME,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS ASC
LIMIT 5;

-- 5. TOP PIZZA BY QUANTITY SOLD
SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 5;

-- 6. WORST PIZZA BY QUANTITY SOLD
SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD ASC
LIMIT 5;

